services:
  notificationsdb:
    image: postgres
    platform: linux/amd64
    restart: always
    ports:
      - 54322:5432
    environment:
      POSTGRES_USER: notifications
      POSTGRES_PASSWORD: notifications

  notifications-service:
    build:
      context: .
      dockerfile: Dockerfile-test
    ports:
      - 18083:18083
    depends_on:
      - notificationsdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://notificationsdb:5432/postgres
      SPRING_DATASOURCE_USERNAME: notifications
      SPRING_DATASOURCE_PASSWORD: notifications
