services:
  userdb:
    image: postgres
    platform: linux/amd64
    restart: always
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user

  users-test:
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      - userdb
