name: Run All Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test-Notifications:
    runs-on: ubuntu-latest
    services:
      notificationsdb:
        image: postgres
        ports:
          - 54322:5432
        env:
          POSTGRES_USER: notifications
          POSTGRES_PASSWORD: notifications
    defaults:
      run:
        working-directory: ./Notifications
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          
      - run: |
          docker-compose -f docker-compose.yml up -d
          
      - run: mvn test

  Test-Offers:
    runs-on: ubuntu-latest
    services:
      offerdb:
        image: postgres
        ports:
          - 54320:5432
        env:
          POSTGRES_USER: offer
          POSTGRES_PASSWORD: offer
    defaults:
      run:
        working-directory: ./Offers
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - run: |
          docker-compose -f docker-compose.yml up -d
          
      - run: mvn test

  Test-Users:
    runs-on: ubuntu-latest
    services:
      userdb:
        image: postgres
        ports:
          - 54321:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: user
    defaults:
      run:
        working-directory: ./Users
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - run: |
          docker-compose -f docker-compose.yml up -d
          
      - run: mvn test
