name: Run All Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test-Notifications:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Notifications
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y docker-compose
      - run: docker-compose -f ./docker-compose-tests.yml up --abort-on-container-exit

  Test-Offers:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Offers
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y docker-compose      
      - run: docker-compose -f ./docker-compose-tests.yml up --abort-on-container-exit

  Test-Users:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Users
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y docker-compose 
      - run: docker-compose -f ./docker-compose-tests.yml up --abort-on-container-exit
