name: Run All Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test-Notifications:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Notifications
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - run: mvn test

  Test-Offers:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Offers
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - run: mvn test

  Test-Users:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Users
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - run: mvn test
